# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 720)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_knn_show = QtWidgets.QPushButton(self.centralwidget)
        self.btn_knn_show.setGeometry(QtCore.QRect(320, 520, 90, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.btn_knn_show.setFont(font)
        self.btn_knn_show.setObjectName("btn_knn_show")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(80, 10, 1121, 491))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.label_img = QtWidgets.QLabel()
        self.label_img.setGeometry(QtCore.QRect(0, 0, 941, 521))
        self.label_img.setObjectName("label_img")
        self.scrollArea.setWidget(self.label_img)
        self.verticalLayout.addWidget(self.scrollArea)
        self.btn_open_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_open_file.setGeometry(QtCore.QRect(80, 520, 80, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.btn_open_file.setFont(font)
        self.btn_open_file.setObjectName("btn_open_file")
        self.label_file_name = QtWidgets.QLabel(self.centralwidget)
        self.label_file_name.setGeometry(QtCore.QRect(80, 650, 671, 25))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_file_name.setFont(font)
        self.label_file_name.setObjectName("label_file_name")
        self.label_teaching = QtWidgets.QLabel(self.centralwidget)
        self.label_teaching.setGeometry(QtCore.QRect(930, 520, 275, 81))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(12)
        self.label_teaching.setFont(font)
        self.label_teaching.setScaledContents(False)
        self.label_teaching.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_teaching.setWordWrap(True)
        self.label_teaching.setObjectName("label_teaching")
        self.btn_ans_show = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ans_show.setGeometry(QtCore.QRect(670, 520, 90, 40))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(10)
        self.btn_ans_show.setFont(font)
        self.btn_ans_show.setObjectName("btn_ans_show")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_knn_show.setText(_translate("MainWindow", "顯示辨識結果"))
        self.label_img.setText(_translate("MainWindow", "TextLabel"))
        self.btn_open_file.setText(_translate("MainWindow", "Open file"))
        self.label_file_name.setText(_translate("MainWindow", "file name："))
        self.label_teaching.setText(_translate("MainWindow", "<html><head/><body><p>使用教學：使用者打開一張清晰的未解數獨的圖片，匯入後，按下顯示辨識結果按鈕，即可導出辨識出來的結果，再按下顯示求解按鈕，則導出求解後的結果。</p></body></html>"))
        self.btn_ans_show.setText(_translate("MainWindow", "顯示求解結果"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
